{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: espresso-shop-postgres-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "espresso-shop.labels" . | nindent 4 }}
    app: espresso-shop-postgres
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    app: espresso-shop-postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.containerPort }}
      protocol: TCP
{{- end }}

