{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: espresso-shop-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "espresso-shop.labels" . | nindent 4 }}
    app: espresso-shop-postgres
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: espresso-shop-postgres
  template:
    metadata:
      labels:
        app: espresso-shop-postgres
    spec:
      serviceAccountName: {{ include "espresso-shop.serviceAccountName" . }}
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.containerPort }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: espresso-shop-postgres-secret
          {{- if .Values.postgres.persistence.enabled }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          {{- end }}
          {{- with .Values.postgres.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.postgres.persistence.enabled }}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: espresso-shop-postgres-pvc
      {{- end }}
{{- end }}

