{{- if and .Values.postgres.enabled .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: espresso-shop-postgres-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "espresso-shop.labels" . | nindent 4 }}
    app: espresso-shop-postgres
spec:
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}
  {{- if .Values.postgres.persistence.storageClassName }}
  storageClassName: {{ .Values.postgres.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- end }}

