apiVersion: v1
kind: Service
metadata:
  name: espresso-shop-reviews-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "espresso-shop.labels" . | nindent 4 }}
    app: espresso-shop-reviews
spec:
  type: {{ .Values.shopReviews.service.type }}
  selector:
    app: espresso-shop-reviews
  ports:
    - name: http
      port: {{ .Values.shopReviews.service.port }}
      targetPort: {{ .Values.shopReviews.containerPort }}
      protocol: TCP

